baseURL = "https://yamatokat.github.io/blog2025/"
languageCode = "ja"
title = "My Blog"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "ようこそ", Content = "これはテストブログです。" }

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "記事一覧"
    url = "/posts/"